import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Noto_Sans, Noto_Sans_Mono } from 'next/font/google';
 
export const noto_sans = Noto_Sans({
  subsets: ['latin'],
  display: 'swap',
})
 
export const noto_sans_mono = Noto_Sans_Mono({
  subsets: ['latin'],
  display: 'swap',
})

import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${noto_sans} ${noto_sans_mono} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
